// AUTH ACTIONS
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILURE = 'REQUEST_LOGIN_FAILURE';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';

// SIGN UP ACTION TYPES
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const REQUEST_SIGN_UP_SUCCESS = 'REQUEST_SIGN_UP_SUCCESS';
export const REQUEST_SIGN_UP_FAILURE = 'REQUEST_SIGN_UP_FAILURE';

// RANKING ACTION TYPES
export const REQUEST_GET_RANKING = 'REQUEST_GET_RANKING';
export const REQUEST_GET_RANKING_SUCCESS = 'REQUEST_GET_RANKING_SUCCESS';
export const REQUEST_GET_RANKING_FAILURE = 'REQUEST_GET_RANKING_FAILURE';

// TRIPS ALL ACTION TYPES
export const REQUEST_GET_TRIPS_ALL = 'REQUEST_GET_TRIPS_ALL';
export const REQUEST_GET_TRIPS_ALL_SUCCESS = 'REQUEST_GET_TRIPS_ALL_SUCCESS';
export const REQUEST_GET_TRIPS_ALL_FAILURE = 'REQUEST_GET_TRIPS_ALL_FAILURE';

// TRIPS INTERVAL ACTION TYPES
export const REQUEST_GET_TRIPS_INTERVAL = 'REQUEST_GET_TRIPS_INTERVAL';
export const REQUEST_GET_TRIPS_INTERVAL_SUCCESS = 'REQUEST_GET_TRIPS_INTERVAL_SUCCESS';
export const REQUEST_GET_TRIPS_INTERVAL_FAILURE = 'REQUEST_GET_TRIPS_INTERVAL_FAILURE';

// TRIPS INFO ACTION TYPES
export const REQUEST_GET_TRIPS_INFO = 'REQUEST_GET_TRIPS_INFO';
export const REQUEST_GET_TRIPS_INFO_SUCCESS = 'REQUEST_GET_TRIPS_INFO_SUCCESS';
export const REQUEST_GET_TRIPS_INFO_FAILURE = 'REQUEST_GET_TRIPS_INFO_FAILURE';

// GRAPH TRIPS SCORE
export const REQUEST_GET_GRAPH_TRIPSCORE = 'REQUEST_GET_GRAPH_TRIPSCORE';
export const REQUEST_GET_GRAPH_TRIPSCORE_SUCCESS = 'REQUEST_GET_GRAPH_TRIPSCORE_SUCCESS';
export const REQUEST_GET_GRAPH_TRIPSCORE_FAILURE = 'REQUEST_GET_GRAPH_TRIPSCORE_FAILURE';

// UI ACTION TYPES
export const OPEN_INVALID_CREDENTIALS_MODAL = 'OPEN_INVALID_CREDENTIALS_MODAL';
export const CLOSE_INVALID_CREDENTIALS_MODAL = 'CLOSE_INVALID_CREDENTIALS_MODAL';
