import {
  REQUEST_LOGIN,
  REQUEST_LOGIN_SUCCESS,
  REQUEST_LOGIN_FAILURE,
  REQUEST_GET_RANKING,
  REQUEST_GET_RANKING_SUCCESS,
  REQUEST_GET_RANKING_FAILURE,
  REQUEST_GET_EVENT,
  REQUEST_GET_EVENT_SUCCESS,
  REQUEST_GET_EVENT_FAILURE,
  REQUEST_GET_TRIPS_ALL,
  REQUEST_GET_TRIPS_ALL_SUCCESS,
  REQUEST_GET_TRIPS_ALL_FAILURE,
  REQUEST_GET_TRIPS_INTERVAL,
  REQUEST_GET_TRIPS_INTERVAL_SUCCESS,
  REQUEST_GET_TRIPS_INTERVAL_FAILURE,
  REQUEST_GET_TRIPS_INFO,
  REQUEST_GET_TRIPS_INFO_SUCCESS,
  REQUEST_GET_TRIPS_INFO_FAILURE,
  REQUEST_GET_GRAPH_TRIPSCORE,
  REQUEST_GET_GRAPH_TRIPSCORE_SUCCESS,
  REQUEST_GET_GRAPH_TRIPSCORE_FAILURE,
} from 'ldmaapp/src/actions/actionTypes';

const loading = (state = false, action) => {
  switch (action.type) {
    case REQUEST_LOGIN:
    case REQUEST_GET_RANKING:
    case REQUEST_GET_EVENT:
    case REQUEST_GET_TRIPS_ALL:
    case REQUEST_GET_TRIPS_INTERVAL:
    case REQUEST_GET_TRIPS_INFO:
    case REQUEST_GET_GRAPH_TRIPSCORE:
      return true;
    case REQUEST_LOGIN_SUCCESS:
    case REQUEST_LOGIN_FAILURE:
    case REQUEST_GET_RANKING_SUCCESS:
    case REQUEST_GET_RANKING_FAILURE:
    case REQUEST_GET_EVENT_SUCCESS:
    case REQUEST_GET_EVENT_FAILURE:
    case REQUEST_GET_TRIPS_ALL_SUCCESS:
    case REQUEST_GET_TRIPS_ALL_FAILURE:
    case REQUEST_GET_TRIPS_INTERVAL_SUCCESS:
    case REQUEST_GET_TRIPS_INTERVAL_FAILURE:
    case REQUEST_GET_TRIPS_INFO_SUCCESS:
    case REQUEST_GET_TRIPS_INFO_FAILURE:
    case REQUEST_GET_GRAPH_TRIPSCORE_SUCCESS:
    case REQUEST_GET_GRAPH_TRIPSCORE_FAILURE:
      return false;
    default:
      return state;
  }
};

export default loading;
